# url: "https://navars.xyz"
theme: minima
# paginate: 5
# paginate_path: "/research/page:num"

collections:
  - publications

collections:
  publications:
    output: true

# sass:
#   style: compressedme
#   source_dir: _sass

# plugins:
#   - jekyll-sitemap
#   - jekyll-paginate
#   - jekyll-feed
#   - jekyll-seo-tag
#   - jekyll-scholar
#   - kramdown-parser-gfm

exclude:
#   - clean-theme.gemspec
  - .jekyll-cache/
  - .sass-cache/
  - Gemfile
  - Gemfile.lock
  # - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

# Build settings
markdown: kramdown
permalink: pretty

# defaults:
#   - scope:
#       path: ""
#       type: "posts"
#     values:
#       permalink: ""

# sass:
#   style: compressedme
#   source_dir: _sass

